# Generated by Django 2.1.5 on 2019-02-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GulleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='student',
            new_name='teacher',
        ),
    ]
